import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src='https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js' />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
